image: docker:latest
services:
  - docker:dind
build:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$([[ ! -z $CI_BUILD_TAG ]] && echo $CI_BUILD_TAG || echo 'latest') .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$([[ ! -z $CI_BUILD_TAG ]] && echo $CI_BUILD_TAG || echo 'latest')
