#!/bin/sh

set -e
source /etc/envvars
if [ ! -z "$XDEBUG_IDE_KEY" ]; then
      # Enable Xdebug by env variables :

      if [ "$(dig docker.for.mac.localhost | grep 'ANSWER SECTION' | wc -l)" -eq 1 ]; then
        DOCKER_HOST=$( dig +short docker.for.mac.localhost)
      else
        DOCKER_HOST=$(ip addr | grep eth0 | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | head -n 1)".1";
      fi
      export XDEBUG_CONFIG="remote_enable=1 remote_mode=req remote_port=9000 remote_host=${DOCKER_HOST} remote_connect_back=0 idekey=${XDEBUG_IDE_KEY}";
      export XDEBUG_REMOTE_HOST="${DOCKER_HOST}";
fi

export APACHE_RUN_USER=apache
export APACHE_RUN_GROUP=www-data
export APACHE_PID_FILE=/web/run/apache2.pid
export APACHE_RUN_DIR=/var/run/
export APACHE_LOCK_DIR=/var/lock/
export APACHE_LOG_DIR=/web/log/

export LANG=C
export LANG

exec /usr/sbin/httpd -DNO_DETACH -f /web/config/httpd.conf